# Generated by Django 4.1.5 on 2023-03-31 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentor", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="onboardingstatus",
            unique_together={("stage", "onboarding")},
        ),
    ]
