# Generated by Django 4.1.5 on 2023-03-31 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mentor", "0002_alter_onboardingstatus_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboarding",
            name="contract_done",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="onboarding",
            name="interview_done",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="onboarding",
            name="offer_done",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboardings",
                to="mentor.mentor",
            ),
        ),
        migrations.DeleteModel(
            name="OnboardingStatus",
        ),
    ]
